In [ ]:
/********************实验五我的答案********************/

--1.找出所有教“数据库”的老师
select Teac_name from CourseTeacher inner join Teacher 
on CourseTeacher.Teac_id = Teacher.Teac_id 
inner join Course on Course.Course_id = CourseTeacher.Course_id
where Course.Course_name = '数据库原理'

--2.找出学号为“130101011”的学生选修课程号和课程名
select * from Student where stu_id ='130101011'

--3.“涂杰杰”所选课程以及成绩
select Course_id,Grade,[StudentGrade].Stu_id from [dbo].[StudentGrade]
inner join Student 
on Student.Stu_id=[StudentGrade].Stu_id
where Stu_name='涂杰杰'

--4.找出“苏贤兴”同学所学课程的名称和成绩
select [Course].[Course_name],[StudentGrade].[Grade]  from [dbo].[Course] inner join [dbo].[StudentGrade]
on [Course].Course_id=[StudentGrade].Course_id  inner join Student 
on Student.Stu_id=[StudentGrade].Stu_id
where Stu_name='苏贤兴'

--5.显示所有课程号，课程名，外加一列，若有人选标出已选
select course_id ,course_name,
case when course_id in (select course_id from StudentGrade ) then '已选'  
end as 选课情况
from course

--6.检索选修课程“0109”和“0111”的学生学号、姓名、所在班级编号
select stu_id,stu_name,[Class_id] from student where 
stu_id in
(select stu_id  from studentGrade where [Course_id]='C0109' and 
stu_id  in (select stu_id  from studentGrade where [Course_id]='C0111'))

--7.找出选修了以“01”开头的课程的学生信息
select * from student where 
stu_id in
(select stu_id  from studentGrade where [Course_id]  like 'C01%' )

--8.找出选修不以“01”开头的课程的学生信息
select * from student where 
stu_id not in
(select stu_id  from studentGrade where [Course_id]  like 'C01%' )
/*这里一定要改not in 或not exists 因为一个人会选多门课，不能出现只要
有选C02等开头就算进去的情况*/

--9.检索既选修了‘数据结构’又选修了‘C语言’的学生学号
select stu_id from StudentGrade where stu_id in(
select StudentGrade.stu_id from StudentGrade inner join  [dbo].[Course] on 
StudentGrade.Course_id=Course.Course_id where [Course_name]='数据结构' 
intersect
select StudentGrade.stu_id from StudentGrade inner join  [dbo].[Course] on 
StudentGrade.Course_id=Course.Course_id where [Course_name]='C语言' )
/*代码没问题，压根没有c语言的课*/

--10.检索选修了‘0103’和‘0105’两门课程，且前者成绩高于后者的学生学号
select A.Stu_id from [dbo].[StudentGrade] A inner join [dbo].[StudentGrade] B
on A.Stu_id=B.Stu_id where A.Course_id ='C0103'and B.Course_id='C0105' and A.[Grade]>B.[Grade]

--11.检索选修了‘数据结构’和‘C语言’两门课程，且前者成绩高于后者的学生学号和姓名
--将student表和StudentGrade用学号连接起来
/*这一题where后面返回选两门课的学号，而第一行用inner jion 会导致学号多次重复出现，后面用ID in 只能选出有选两门课的学生，
并不能消重，所以前面要用distinct*/
select distinct(student.stu_id),student.stu_name from student inner join  StudentGrade
on student.stu_id=StudentGrade.stu_id
--索引出符合题目的学生ID
where student.stu_id in(
--studentGrade用学号自连接
select A.Stu_id from [dbo].[StudentGrade] A inner join [dbo].[StudentGrade] B
on A.Stu_id=B.Stu_id 
--用A表锁定数据结构
where A.Course_id =(select Course_id from course where [Course_name]='数据结构')
--用B表锁定数据库原理
and B.Course_id=(select Course_id from course where [Course_name]='数据库原理') 
--数据结构成绩大于数据库原理
and A.[Grade]>B.[Grade])